on:
  push:
    branches:
    - main
    paths:
    - cv.pdf
  workflow_dispatch:

name: Upload to GCS

env:
  BUCKET_NAME: yavrumian.com
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
      with:
        version: latest
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY }}
        export_default_credentials: true

    - uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@0.1.3
      with:
        path: cv.pdf
        destination: ${{ env.BUCKET_NAME }}